spring:
  profiles:
    active: ${ACTIVE}
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: com.xunlekj.jpa.naming.CustomNamingStrategy
security:
  token:
    subject: vehicle
    issuer: https://www.xunlekj.com
